import org.box2d.jni.BuildSrc
import org.box2d.jni.android.LocalProperties

plugins {
    alias(libs.plugins.android.library) // to build Android libraries
}
LocalProperties.checkLocalProperties(
    project
)

description = 'box2d-jni android'

ext {
    baseName = "${artifact}" // for artifacts
    libraryVersion = "${jjVersion}"
    groupID = 'io.github.jnightrider'
}

android {
    namespace = groupID + '.box2djni'
    compileSdk = 36

    defaultConfig {
        minSdk = 35
        targetSdk = 36
        versionCode = 1
        versionName = libraryVersion
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            ndk {
                def target = findProperty('box2d.jni.android.target')
                if (!target) {
                    abiFilters 'arm64-v8a', 'armeabi-v7a', 'riscv64', 'x86', 'x86_64'
                } else if (target == 'Android_ARM7') {
                    abiFilters 'armeabi-v7a'
                } else if (target == 'Android_ARM8') {
                    abiFilters 'arm64-v8a'
                } else if (target == 'Android_RISCV64') {
                    abiFilters 'riscv64'
                } else if (target == 'Android_X86') {
                    abiFilters 'x86'
                } else if (target == 'Android_X86_64') {
                    abiFilters 'x86_64'
                }
            }
            cmake {
                cFlags "-std=c11"
                arguments "-DBINDINGS_ANDROID_HOME=${BuildSrc.getToolchainDir()}"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "${rootDir}/modules/libraries/box2d-bindings/c/CMakeLists.txt"
        }
    }

    flavorDimensions += "precision"

    productFlavors {
        def flavor = findProperty('box2d.jni.flavor')
        if (!flavor || flavor == 'Dp') {
            dp {
                dimension "precision"
                externalNativeBuild {
                    cmake {
                        arguments "-DBOX2D_DOUBLE_PRECISION=ON"
                    }
                }
            }
        }
        if (!flavor || flavor == 'Sp') {
            sp {
                dimension "precision"
                externalNativeBuild {
                    cmake {
                        arguments "-DBOX2D_DOUBLE_PRECISION=OFF"
                    }
                }
            }
        }
    }

    buildTypes {
        def bt = findProperty('box2d.jni.bt')
        if (!bt || bt == 'Debug') {
            debug {
                externalNativeBuild {
                    cmake {
                        arguments "-DTYPE_DEBUG=ON"
                    }
                }
            }
        }

        if (!bt || bt == 'Release') {
            release {
                minifyEnabled true
                externalNativeBuild {
                    cmake {
                        arguments "-DTYPE_DEBUG=OFF"
                    }
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = true
    }
}

afterEvaluate {
    tasks.matching {
        it.name.startsWith("bundle") && it.name.endsWith("Aar")
    }.configureEach { task ->
        def variantName = task.name.substring("bundle".length()).replace("Aar", "")
        def variant = BuildSrc.checkAndroidVariantName(variantName)

        task.archiveFileName.set("box2d-jni-${jjVersion}-android_${variant}.aar")
    }
}

tasks.register("copyAars", Copy) {
    from(layout.buildDirectory.dir("outputs/aar"))
    exclude("box2d-jni-${jjVersion}-android-.aar")
    into("${rootDir}/lib")
}

tasks.configureEach { task ->
    if (task.name.startsWith("bundle") && task.name.endsWith("Aar")) {
        task.finalizedBy("copyAars")
    }
}

tasks.named("preBuild") {
    dependsOn(
        ':modules:libraries:box2d-bindings:unpackBox2dSource',
        ':modules:libraries:box2d-bindings:unpackLibffiSource',
        ':modules:libraries:box2d-core:classes'
    )
}

dependencies {
    androidTestImplementation project(':modules:libraries:box2d-core')

    testImplementation libs.junit4

    androidTestImplementation libs.android.ext.junit
    androidTestImplementation libs.android.test.runner
    androidTestImplementation libs.android.test.rules
    androidTestImplementation libs.android.espresso.core
}
