plugins {
    alias(libs.plugins.android.library) // to build Android libraries
}

description = 'box2d-jni android'

ext {
    baseName = "${artifact}" // for artifacts
    groupID = 'io.github.jnightrider'
}

android {
    namespace = groupID + '.box2djni'
    compileSdk = 36

    defaultConfig {
        minSdk = 35
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        externalNativeBuild {
            ndk {
                def target = findProperty('box2d.jni.android.target')
                if (!target) {
                    abiFilters 'arm64-v8a', 'armeabi-v7a', 'riscv64', 'x86', 'x86_64'
                } else if (target == 'Android_ARM7') {
                    abiFilters 'armeabi-v7a'
                } else if (target == 'Android_ARM8') {
                    abiFilters 'arm64-v8a'
                } else if (target == 'Android_RISCV64') {
                    abiFilters 'riscv64'
                } else if (target == 'Android_X86') {
                    abiFilters 'x86'
                } else if (target == 'Android_X86_64') {
                    abiFilters 'x86_64'
                }
            }
            cmake {
                cFlags "-std=c11"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "${rootDir}/modules/libraries/box2d-bindings/c/CMakeLists.txt"
        }
    }

    flavorDimensions += "precision"

    productFlavors {
        def flavor = findProperty('box2d.jni.flavor')
        if (!flavor || flavor == 'Dp') {
            dp {
                dimension "precision"
                externalNativeBuild {
                    cmake {
                        arguments "-DBOX2D_DOUBLE_PRECISION=ON"
                    }
                }
            }
        }
        if (!flavor || flavor == 'Sp') {
            sp {
                dimension "precision"
                externalNativeBuild {
                    cmake {
                        arguments "-DBOX2D_DOUBLE_PRECISION=OFF"
                    }
                }
            }
        }
    }

    buildTypes {
        debug {
            externalNativeBuild {
                cmake {
                    arguments "-DTYPE_DEBUG=ON"
                }
            }
        }

        release {
            minifyEnabled true
            externalNativeBuild {
                cmake {
                    arguments "-DTYPE_DEBUG=OFF"
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {

}