// global build settings for the Box2d-JNI Project

pluginManagement {
    repositories {
        gradlePluginPortal()
        google() // to find plugins released to Google's Maven Repository
        mavenCentral()
    }
}

rootProject.name = 'box2d-jni '

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

def androidEnabled =
        providers.gradleProperty("box2d.jni.android")
                .map { it.toBoolean() }
                .orElse(false)
                .get()

def iosEnabled =
        providers.gradleProperty("box2d.jni.ios")
                .map { it.toBoolean() }
                .orElse(false)
                .get()

include ':modules:libraries:box2d-core'
include ':modules:libraries:box2d-bindings'

// Check which platforms need to be skipped.
if (androidEnabled) {
    include ':modules:libraries:box2d-android'
}
if (iosEnabled) {
    include ':modules:libraries:box2d-ios'
}

include ':modules:samples'