/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_MemoryUtil */

#ifndef _Included_org_box2d_jni_system_MemoryUtil
#define _Included_org_box2d_jni_system_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_system_MemoryUtil
 * Method:    nGetStringUTFChars
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_MemoryUtil_nGetStringUTFChars
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_box2d_jni_system_MemoryUtil
 * Method:    nReleaseStringUTFChars
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_MemoryUtil_nReleaseStringUTFChars
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_box2d_jni_system_MemoryUtil
 * Method:    nNewStringUTF
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_box2d_jni_system_MemoryUtil_nNewStringUTF
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
