/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_include_Base */

#ifndef _Included_org_box2d_jni_include_Base
#define _Included_org_box2d_jni_include_Base
#ifdef __cplusplus
extern "C" {
#endif
#undef org_box2d_jni_include_Base_B2_HASH_INIT
#define org_box2d_jni_include_Base_B2_HASH_INIT 5381L
/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2SetAllocator
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Base_nb2SetAllocator
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2GetByteCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Base_nb2GetByteCount
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2SetAssertFcn
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Base_nb2SetAssertFcn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2SetLogFcn
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Base_nb2SetLogFcn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2GetVersion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Base_nb2GetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2GetTicks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Base_nb2GetTicks
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2GetMilliseconds
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_Base_nb2GetMilliseconds
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2GetMillisecondsAndReset
 * Signature: (Ljava/nio/LongBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_Base_nb2GetMillisecondsAndReset
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2Yield
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Base_nb2Yield
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_include_Base
 * Method:    nb2Hash
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_Base_nb2Hash
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
