/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_JNI */

#ifndef _Included_org_box2d_jni_system_JNI
#define _Included_org_box2d_jni_system_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokeJIP
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_JNI_invokeJIP
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokeJJV
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNI_invokeJJV
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokePV
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNI_invokePV
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokePPII
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_system_JNI_invokePPII
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokePPV
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNI_invokePPV
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokePPPP
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_JNI_invokePPPP
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokeFJFJF
 * Signature: (FJFJJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_system_JNI_invokeFJFJF
  (JNIEnv *, jclass, jfloat, jlong, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNI
 * Method:    invokePIIPV
 * Signature: (JIIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNI_invokePIIPV
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
