/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_JNIB2 */

#ifndef _Included_org_box2d_jni_system_JNIB2
#define _Included_org_box2d_jni_system_JNIB2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_SHAPEID_PB
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1SHAPEID_1PB
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_SHAPEID_PPB
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1SHAPEID_1PPB
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_SHAPEID_SHAPEID_PB
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1SHAPEID_1SHAPEID_1PB
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_SHAPEID_SHAPEID_VEC2_VEC2_PB
 * Signature: (JJJJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1SHAPEID_1SHAPEID_1VEC2_1VEC2_1PB
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_SHAPEID_VEC2_VEC2_FPF
 * Signature: (JJJFJJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1SHAPEID_1VEC2_1VEC2_1FPF
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_TRANSFORM_PIFIPV
 * Signature: (JJIFIJJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1TRANSFORM_1PIFIPV
  (JNIEnv *, jclass, jlong, jlong, jint, jfloat, jint, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_TRANSFORM_PV
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1TRANSFORM_1PV
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_TRANSFORM_FIPV
 * Signature: (JFIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1TRANSFORM_1FIPV
  (JNIEnv *, jclass, jlong, jfloat, jint, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_VEC2_FIPV
 * Signature: (JFIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1VEC2_1FIPV
  (JNIEnv *, jclass, jlong, jfloat, jint, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_VEC2_VEC2_FIPV
 * Signature: (JJFIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1VEC2_1VEC2_1FIPV
  (JNIEnv *, jclass, jlong, jlong, jfloat, jint, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_VEC2_VEC2_IPV
 * Signature: (JJIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1VEC2_1VEC2_1IPV
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_JNIB2
 * Method:    invoke_VEC2_PIPV
 * Signature: (JJIJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_JNIB2_invoke_1VEC2_1PIPV
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
