/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_include_Id */

#ifndef _Included_org_box2d_jni_include_Id
#define _Included_org_box2d_jni_include_Id
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreWorldId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_Id_nb2StoreWorldId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadWorldId
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadWorldId
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreBodyId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Id_nb2StoreBodyId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadBodyId
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadBodyId
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreShapeId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Id_nb2StoreShapeId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadShapeId
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadShapeId
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreChainId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Id_nb2StoreChainId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadChainId
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadChainId
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreJointId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_include_Id_nb2StoreJointId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadJointId
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadJointId
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2StoreContactId
 * Signature: (JLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2StoreContactId
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_box2d_jni_include_Id
 * Method:    nb2LoadContactId
 * Signature: (Ljava/nio/IntBuffer;J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Id_nb2LoadContactId
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
