/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_b2JointType */

#ifndef _Included_org_box2d_jni_b2JointType
#define _Included_org_box2d_jni_b2JointType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_distanceJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1distanceJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_filterJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1filterJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_motorJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1motorJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_prismaticJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1prismaticJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_revoluteJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1revoluteJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_weldJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1weldJoint
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2JointType
 * Method:    nb2_wheelJoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2JointType_nb2_1wheelJoint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
