/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_Upcalls */

#ifndef _Included_org_box2d_jni_system_Upcalls
#define _Included_org_box2d_jni_system_Upcalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_void
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1void
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_uint8
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1uint8
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_sint8
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1sint8
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_uint16
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1uint16
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_sint16
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1sint16
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_uint32
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1uint32
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_sint32
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1sint32
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_uint64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1uint64
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_sint64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1sint64
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_float
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1float
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_double
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1double
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_pointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1pointer
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_longdouble
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1longdouble
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_b2ShapeId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1b2ShapeId
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_b2Vec2
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1b2Vec2
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_b2Rot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1b2Rot
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    nffi_type_b2Transform
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_nffi_1type_1b2Transform
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    njniCallbackCreate
 * Signature: (Ljava/lang/Object;JLjava/nio/LongBuffer;J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_njniCallbackCreate
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    njniCallbackFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Upcalls_njniCallbackFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Upcalls
 * Method:    napiClosureFunction
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Upcalls_napiClosureFunction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
