/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_include_Types */

#ifndef _Included_org_box2d_jni_include_Types
#define _Included_org_box2d_jni_include_Types
#ifdef __cplusplus
extern "C" {
#endif
#undef org_box2d_jni_include_Types_B2_DEFAULT_CATEGORY_BITS
#define org_box2d_jni_include_Types_B2_DEFAULT_CATEGORY_BITS 1L
/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultWorldDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultWorldDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultBodyDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultBodyDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultFilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultQueryFilter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultQueryFilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultSurfaceMaterial
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultSurfaceMaterial
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultShapeDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultShapeDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultChainDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultChainDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultDistanceJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultDistanceJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultMotorJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultMotorJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultFilterJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultFilterJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultPrismaticJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultPrismaticJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultRevoluteJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultRevoluteJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultWeldJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultWeldJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultWheelJointDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultWheelJointDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultExplosionDef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultExplosionDef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2GetGraphColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_Types_nb2GetGraphColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_box2d_jni_include_Types
 * Method:    nb2DefaultDebugDraw
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_Types_nb2DefaultDebugDraw
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
