/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_libc_LibCFloat */

#ifndef _Included_org_box2d_jni_libc_LibCFloat
#define _Included_org_box2d_jni_libc_LibCFloat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_libc_LibCFloat
 * Method:    nFLT_EPSILON
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_libc_LibCFloat_nFLT_1EPSILON
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
