/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_libc_LibCStdlib */

#ifndef _Included_org_box2d_jni_libc_LibCStdlib
#define _Included_org_box2d_jni_libc_LibCStdlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_libc_LibCStdlib
 * Method:    nmalloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_libc_LibCStdlib_nmalloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_libc_LibCStdlib
 * Method:    nfree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_libc_LibCStdlib_nfree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
