/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_libc_LibCString */

#ifndef _Included_org_box2d_jni_libc_LibCString
#define _Included_org_box2d_jni_libc_LibCString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_libc_LibCString
 * Method:    nmemset
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_libc_LibCString_nmemset
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_box2d_jni_libc_LibCString
 * Method:    nmemcpy
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_libc_LibCString_nmemcpy
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_libc_LibCString
 * Method:    nstrlen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_libc_LibCString_nstrlen
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
