/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_Memory */

#ifndef _Included_org_box2d_jni_system_Memory
#define _Included_org_box2d_jni_system_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nsizeof
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_system_Memory_nsizeof
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_box2d_jni_system_Memory_ngetByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_org_box2d_jni_system_Memory_ngetShort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_system_Memory_ngetInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Memory_ngetLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_system_Memory_ngetFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_box2d_jni_system_Memory_ngetDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Memory_ngetAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputByte
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputShort
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputShort
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputFloat
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputDouble
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputAddress
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_system_Memory_nputAddress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    ngetNativeAddress
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_system_Memory_ngetNativeAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_box2d_jni_system_Memory
 * Method:    nputNativeAddress
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_box2d_jni_system_Memory_nputNativeAddress
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
