/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_libc_LibCMath */

#ifndef _Included_org_box2d_jni_libc_LibCMath
#define _Included_org_box2d_jni_libc_LibCMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_libc_LibCMath
 * Method:    ncosf
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_libc_LibCMath_ncosf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_libc_LibCMath
 * Method:    nsinf
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_libc_LibCMath_nsinf
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_libc_LibCMath
 * Method:    natan2f
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_libc_LibCMath_natan2f
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
