/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_b2ShapeType */

#ifndef _Included_org_box2d_jni_b2ShapeType
#define _Included_org_box2d_jni_b2ShapeType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_circleShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1circleShape
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_capsuleShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1capsuleShape
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_segmentShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1segmentShape
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_polygonShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1polygonShape
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_chainSegmentShape
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1chainSegmentShape
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2ShapeType
 * Method:    nb2_shapeTypeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2ShapeType_nb2_1shapeTypeCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
