/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_libc_LibCStdint */

#ifndef _Included_org_box2d_jni_libc_LibCStdint
#define _Included_org_box2d_jni_libc_LibCStdint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_libc_LibCStdint
 * Method:    nUINT64_MAX
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_box2d_jni_libc_LibCStdint_nUINT64_1MAX
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
