/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_system_VarType */

#ifndef _Included_org_box2d_jni_system_VarType
#define _Included_org_box2d_jni_system_VarType
#ifdef __cplusplus
extern "C" {
#endif
#undef org_box2d_jni_system_VarType_int8_t
#define org_box2d_jni_system_VarType_int8_t 1L
#undef org_box2d_jni_system_VarType_int16_t
#define org_box2d_jni_system_VarType_int16_t 2L
#undef org_box2d_jni_system_VarType_int32_t
#define org_box2d_jni_system_VarType_int32_t 3L
#undef org_box2d_jni_system_VarType_int64_t
#define org_box2d_jni_system_VarType_int64_t 4L
#undef org_box2d_jni_system_VarType_float_t
#define org_box2d_jni_system_VarType_float_t 5L
#undef org_box2d_jni_system_VarType_double_t
#define org_box2d_jni_system_VarType_double_t 6L
#undef org_box2d_jni_system_VarType_uintptr_t
#define org_box2d_jni_system_VarType_uintptr_t 7L
/*
 * Class:     org_box2d_jni_system_VarType
 * Method:    __nsizeof
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_system_VarType__1_1nsizeof
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
