/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_b2BodyType */

#ifndef _Included_org_box2d_jni_b2BodyType
#define _Included_org_box2d_jni_b2BodyType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_b2BodyType
 * Method:    nb2_staticBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2BodyType_nb2_1staticBody
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2BodyType
 * Method:    nb2_kinematicBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2BodyType_nb2_1kinematicBody
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2BodyType
 * Method:    nb2_dynamicBody
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2BodyType_nb2_1dynamicBody
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_b2BodyType
 * Method:    nb2_bodyTypeCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_b2BodyType_nb2_1bodyTypeCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
