/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_box2d_jni_include_MathFunctions */

#ifndef _Included_org_box2d_jni_include_MathFunctions
#define _Included_org_box2d_jni_include_MathFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nB2_PI
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nB2_1PI
  (JNIEnv *, jclass);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsValidFloat
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsValidFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsValidVec2
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsValidVec2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsValidRotation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsValidRotation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsValidTransform
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsValidTransform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsValidAABB
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsValidAABB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    n2IsValidPlane
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_n2IsValidPlane
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MinInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MinInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MaxInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MaxInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AbsInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AbsInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2ClampInt
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_MathFunctions_nb2ClampInt
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2CeilingInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_box2d_jni_include_MathFunctions_nb2CeilingInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MinFloat
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MinFloat
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MaxFloat
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MaxFloat
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AbsFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AbsFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2ClampFloat
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2ClampFloat
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Atan2
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Atan2
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2ComputeCosSin
 * Signature: (FJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2ComputeCosSin
  (JNIEnv *, jclass, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Dot
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Dot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Cross
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Cross
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2CrossVS
 * Signature: (JFJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2CrossVS
  (JNIEnv *, jclass, jlong, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2CrossSV
 * Signature: (FJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2CrossSV
  (JNIEnv *, jclass, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2LeftPerp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2LeftPerp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2RightPerp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2RightPerp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Add
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Neg
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Neg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Lerp
 * Signature: (JJFJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Lerp
  (JNIEnv *, jclass, jlong, jlong, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Mul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Mul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulSV
 * Signature: (FJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulSV
  (JNIEnv *, jclass, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulAdd
 * Signature: (JFJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulAdd
  (JNIEnv *, jclass, jlong, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulSub
 * Signature: (JFJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulSub
  (JNIEnv *, jclass, jlong, jfloat, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Abs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Abs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Min
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Min
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Max
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Max
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Clamp
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Clamp
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Length
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Length
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Distance
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Distance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Normalize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Normalize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsNormalized
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsNormalized
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2GetLengthAndNormalize
 * Signature: (Ljava/nio/FloatBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2GetLengthAndNormalize
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2NormalizeRot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2NormalizeRot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IntegrateRotation
 * Signature: (JFJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IntegrateRotation
  (JNIEnv *, jclass, jlong, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2LengthSquared
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2LengthSquared
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2DistanceSquared
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2DistanceSquared
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MakeRot
 * Signature: (FJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MakeRot
  (JNIEnv *, jclass, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MakeRotFromUnitVector
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MakeRotFromUnitVector
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2ComputeRotationBetweenUnitVectors
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2ComputeRotationBetweenUnitVectors
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2IsNormalizedRot
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2IsNormalizedRot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2InvertRot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2InvertRot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2NLerp
 * Signature: (JJFJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2NLerp
  (JNIEnv *, jclass, jlong, jlong, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2ComputeAngularVelocity
 * Signature: (JJF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2ComputeAngularVelocity
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Rot_GetAngle
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Rot_1GetAngle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Rot_GetXAxis
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Rot_1GetXAxis
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Rot_GetYAxis
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Rot_1GetYAxis
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulRot
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulRot
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2InvMulRot
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2InvMulRot
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2RelativeAngle
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2RelativeAngle
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2UnwindAngle
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2UnwindAngle
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2RotateVector
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2RotateVector
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2InvRotateVector
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2InvRotateVector
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2TransformPoint
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2TransformPoint
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2InvTransformPoint
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2InvTransformPoint
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulTransforms
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulTransforms
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2InvMulTransforms
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2InvMulTransforms
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MulMV
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MulMV
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2GetInverse22
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2GetInverse22
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2Solve22
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2Solve22
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AABB_Contains
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AABB_1Contains
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AABB_Center
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AABB_1Center
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AABB_Extents
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AABB_1Extents
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AABB_Union
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AABB_1Union
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2AABB_Overlaps
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_box2d_jni_include_MathFunctions_nb2AABB_1Overlaps
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2MakeAABB
 * Signature: (JIFJ)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2MakeAABB
  (JNIEnv *, jclass, jlong, jint, jfloat, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2PlaneSeparation
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2PlaneSeparation
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2SpringDamper
 * Signature: (FFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2SpringDamper
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2SetLengthUnitsPerMeter
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_box2d_jni_include_MathFunctions_nb2SetLengthUnitsPerMeter
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_box2d_jni_include_MathFunctions
 * Method:    nb2GetLengthUnitsPerMeter
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_box2d_jni_include_MathFunctions_nb2GetLengthUnitsPerMeter
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
