buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        // Plugin de RoboVM (MobiVM) for Gradle
        classpath 'com.mobidevelop.robovm:robovm-gradle-plugin:2.3.26'
    }
}

plugins {
    id 'java'
    id 'iOS'
}

apply plugin: 'robovm'

description = 'box2d-jni ios'

ext {
    baseName = "${artifact}" // for artifacts
    libraryVersion = "${jjVersion}"
    groupID = 'io.github.jnightrider'
}

ios {
    miVersion = '15.0'

    def target = findProject('box2d.jni.ios.target')
    if (!target) {
        devices 'device-arm64', 'arm64', 'x86_64'
    } else if (target == 'Device_ARM64') {
        devices 'device-arm64'
    } else if (target == 'Simulator_ARM64') {
        devices 'arm64'
    } else if (target == 'Simulator_x86_64') {
        devices 'x86_64'
    }

    cmake {
        workingDir = "${rootDir}/modules/libraries/box2d-bindings/c"
        outputDir = "${layout.buildDirectory.asFile.get()}/cxx"
    }

    buildTypes {
        debug {
            arguments '-DTYPE_DEBUG=ON'
        }
        release {
            arguments '-DTYPE_DEBUG=OFF'
        }
    }

    productFlavors {
        dp {
            arguments '-DBOX2D_DOUBLE_PRECISION=ON'
        }
        sp {
            arguments '-DBOX2D_DOUBLE_PRECISION=OFF'
        }
    }
}

dependencies {
    // RoboVM runtime base libraries
    testImplementation 'com.mobidevelop.robovm:robovm-rt:2.3.26'
    testImplementation 'com.mobidevelop.robovm:robovm-cocoatouch:2.3.26'
}

// RoboVM Ahead-Of-Time (AOT) Compiler Configuration
robovm {
    // It points to the application configuration properties file for iOS.
    configFile = file('robovm.properties')

    iosSignIdentity = ""
    iosProvisioningProfile = ""
    iosSkipSigning = true // Change to false when compiling for the App Store or a real device.
}
