## iOS Configuration
# App name and identifier
app.id=com.miempresa.mijuego
app.name=Box2dJNIVM
app.mainclass=com.miempresa.mijuego.IOSLauncher

# Minimum iOS version required
app.version=15.0
app.build=15
app.executable=Box2dJNIVM
