## iOS Configuration
# App name and identifier
app.id=corg.box2d.jni.test
app.name=Box2dJNIVM
app.mainclass=org.box2d.jni.test.Main

# Minimum iOS version required
app.version=15.0
app.build=15
app.executable=Box2dJNIVM
