/*
BSD 3-Clause License

Copyright (c) 2026, Night Rider

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
package org.box2d.jni.android;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

import org.box2d.jni.BuildSrc;

import org.gradle.api.Project;

/**
 *
 * @author wil
 * @version 1.0.0
 * @since 1.3.0
 */
public final class LocalProperties {

    private static final System.Logger LOG = System.getLogger(LocalProperties.class.getName());
    
    private static final String LOCAL_PROPERTIES_NAME = "local.properties";
    private static final String ANDROID_HOME;
    
    static {
        String sdk = System.getenv("ANDROID_HOME");
        if (sdk == null) {
            sdk = System.getenv("ANDROID_SDK_ROOT");
        }
        if (sdk == null) {
            String userHome = System.getProperty("user.home", "");
            String os = System.getProperty("os.name").toLowerCase();

            sdk = userHome + File.separator;
            if (os.contains("win")) {
                sdk += "AppData/Local/Android/Sdk";
            } else if (os.contains("mac")) {
                sdk += "Library/Android/sdk";
            } else if (os.contains("linux")) {
                sdk += "Android/Sdk";
            } else {
                throw new UnsupportedOperationException("ANDROID_HOME");
            }
        }        
        ANDROID_HOME = sdk;        
    }

    public static void checkLocalProperties(Project project, File rootDir) {
        Object check = project.findProperty("box2d.jni.android.check");
        if (check == null || rootDir == null) {
            LOG.log(System.Logger.Level.INFO, "Android SDK search disabled");
            return;
        }

        if (!rootDir.exists() || !rootDir.isDirectory()) {
            LOG.log(System.Logger.Level.WARNING, () -> "The project root directory is invalid: rootDir=" + rootDir);
            return;
        }

        if (BuildSrc.checkBool("true")) {
            File file = new File(rootDir, LOCAL_PROPERTIES_NAME);
            if (! file.exists()) {
                createLocalProperties(file);
            } else {
                printLocalProperties(file);
            }
        }
    }

    private static void printLocalProperties(File file) {
        try (InputStream in = new FileInputStream(file)) {
            Properties properties = new Properties();
            properties.load(in);

            System.out.println("> sdk :ANDROID_HOME=" + properties.getProperty("sdk.dir"));
        } catch (Exception ex) { /* ignore */ }
    }

    private static void createLocalProperties(File file) {
        Properties properties = new Properties();
        properties.put("sdk.dir", ANDROID_HOME);
        
        try (OutputStream out = new FileOutputStream(file)) {
            properties.store(out,
"""
## This file is automatically generated by Box2d-JNI.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
"""
            );
        } catch (Exception e) {
            LOG.log(System.Logger.Level.WARNING, "Error creating the properties file of ANDROID_HOME");
        }
    }
}
