plugins {
    id 'java-gradle-plugin'
}

description = 'box2d-jni build'

gradlePlugin {
    plugins {
        iOSPlugin {
            id = 'iOS'
            implementationClass = 'org.box2d.jni.ios.IOS'
        }
    }
}


repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
}
