---
# GitHub Actions workflow for commits pushed to the box2d-jni repo - all branches

name: CI at GitHub
on: [push, workflow_dispatch]

jobs:
  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libffi-dev \
            pkg-config \
            cmake
      
      - uses: gradle/actions/setup-gradle@v4
      - name: Verify toolchain
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          gcc --version
          cmake --version
          pkg-config --modversion libffi
      
      - name: gradlew build
        #if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          ./gradlew build \
            --console=plain
      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: box2d-jni-linux
          path: lib/*.jar
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            modules/libraries/box2d-core/build/reports/tests/test
          if-no-files-found: ignore
          
  Java21-Windows64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-libffi
            mingw-w64-x86_64-pkgconf

      - uses: gradle/actions/setup-gradle@v4

      - name: Verify toolchain
        shell: bash
        run: |
          java -version
          gcc --version
          cmake --version
          pkg-config --version
          pkg-config --modversion libffi || true

      - name: gradlew build
        #if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
            ./gradlew build \
            --console=plain

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: box2d-jni-windows
          path: lib/*.jar

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-windows
          path: |
            modules/libraries/box2d-core/build/reports/tests/test
          if-no-files-found: ignore
